Microsoft Windows [Version 10.0.17763.805]                                                                              (c) 2018 Microsoft Corporation. All rights reserved.                                                                                                                                                                                            C:\Users\kevin>cd Desktop                                                                                                                                                                                                                       C:\Users\kevin\Desktop>cd codingDojo                                                                                                                                                                                                            C:\Users\kevin\Desktop\codingDojo>python manage.py shell                                                                python: can't open file 'manage.py': [Errno 2] No such file or directory                                                                                                                                                                        C:\Users\kevin\Desktop\codingDojo>cd "Python Stack"                                                                                                                                                                                             C:\Users\kevin\Desktop\codingDojo\Python Stack>python manage.py shell                                                   python: can't open file 'manage.py': [Errno 2] No such file or directory                                                                                                                                                                        C:\Users\kevin\Desktop\codingDojo\Python Stack>call my_environments/djangopy3Env/scripts/activate                                                                                                                                               (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack>cd django                                                                                                                                                                         (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django>cd django_intro                                                                                                                                                            (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_intro>cd ..                                                                                                                                                         (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django>cd django_orm                                                                                                                                                              (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm>django-admin startproject ORM_1                                                                                                                                 (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm>cd ORM_1                                                                                                                                                        (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1>mkdir apps                                                                                                                                                (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1>cd apps                                                                                                                                                   (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1\apps>python ../manage.py startapp APP_1                                                                                                                                                                                                                                           (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1\apps>cd ..                                                                                                                                                (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1>cd apps                                                                                                                                                   (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1\apps>cd APP_1                                                                                                                                             (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1\apps\APP_1>type nul > urls.py                                                                                                                             (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1\apps\APP_1>cd ..                                                                                                                                          (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1\apps>cd ..                                                                                                                                                (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1>code .                                                                                                                                                    (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1>python manage.py makemigrations   Traceback (most recent call last):                                                                                        File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\apps\config.py", line 118, in create                                                                                                   cls = getattr(mod, cls_name)                                                                                        AttributeError: module 'apps' has no attribute 'APP_!'                                                                                                                                                                                          During handling of the above exception, another exception occurred:                                                                                                                                                                             Traceback (most recent call last):                                                                                        File "manage.py", line 22, in <module>                                                                                    execute_from_command_line(sys.argv)                                                                                   File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line                                                                   utility.execute()                                                                                                     File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 341, in execute                                                                                     django.setup()                                                                                                        File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\__init__.py", line 27, in setup                                                                                                        apps.populate(settings.INSTALLED_APPS)                                                                                File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\apps\registry.py", line 85, in populate                                                                                                app_config = AppConfig.create(entry)                                                                                  File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\apps\config.py", line 123, in create                                                                                                   import_module(entry)                                                                                                  File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked                                            ModuleNotFoundError: No module named 'apps.APP_!'                                                                                                                                                                                               (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1>python manage.py makemigrations   Traceback (most recent call last):                                                                                        File "manage.py", line 22, in <module>                                                                                    execute_from_command_line(sys.argv)                                                                                   File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line                                                                   utility.execute()                                                                                                     File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 341, in execute                                                                                     django.setup()                                                                                                        File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\__init__.py", line 27, in setup                                                                                                        apps.populate(settings.INSTALLED_APPS)                                                                                File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\apps\registry.py", line 108, in populate                                                                                               app_config.import_models(all_models)                                                                                  File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\apps\config.py", line 199, in import_models                                                                                            self.models_module = import_module(models_module_name)                                                                File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1\apps\APP_1\models.py", line 4, in <module>                                                                                                                           class Hogwarts(models.Model):                                                                                         File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1\apps\APP_1\models.py", line 5, in Hogwarts                                                                                                                           name = models.Charfield(max_length = 45)                                                                            AttributeError: module 'django.db.models' has no attribute 'Charfield'                                                                                                                                                                          (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1>python manage.py makemigrations   Migrations for 'APP_1':                                                                                                   apps\APP_1\migrations\0001_initial.py:                                                                                    - Create model Hogwarts                                                                                                                                                                                                                     (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1>python manage.py migrate          Operations to perform:                                                                                                    Apply all migrations: APP_1, admin, auth, contenttypes, sessions                                                      Running migrations:                                                                                                       Rendering model states... DONE                                                                                          Applying APP_1.0001_initial... OK                                                                                       Applying contenttypes.0001_initial... OK                                                                                Applying auth.0001_initial... OK                                                                                        Applying admin.0001_initial... OK                                                                                       Applying admin.0002_logentry_remove_auto_add... OK                                                                      Applying contenttypes.0002_remove_content_type_name... OK                                                               Applying auth.0002_alter_permission_name_max_length... OK                                                               Applying auth.0003_alter_user_email_max_length... OK                                                                    Applying auth.0004_alter_user_username_opts... OK                                                                       Applying auth.0005_alter_user_last_login_null... OK                                                                     Applying auth.0006_require_contenttypes_0002... OK                                                                      Applying auth.0007_alter_validators_add_error_messages... OK                                                            Applying auth.0008_alter_user_username_max_length... OK                                                                 Applying sessions.0001_initial... OK                                                                                                                                                                                                          (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1>manage.py shell                   Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32                       Type "help", "copyright", "credits" or "license" for more information.                                                  (InteractiveConsole)                                                                                                    >>>                                                                                                                     KeyboardInterrupt                                                                                                       >>>                                                                                                                     KeyboardInterrupt                                                                                                       >>>                                                                                                                     KeyboardInterrupt                                                                                                       >>> exit                                                                                                                Use exit() or Ctrl-Z plus Return to exit                                                                                >>> exit()                                                                                                                                                                                                                                      (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\ORM_1>cd ..                                                                                                                                                     (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm>django-admin startproject single_model_orm                                                                                                                                                                                                                                              (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm>cd single_model_orm                                                                                                                                             (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>mkdir apps                                                                                                                                     (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>cd apps                                                                                                                                        (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps>python ../manage.py startapp users_app                                                                                                                                                                                                                            (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps>cd users_app                                                                                                                              (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps\users_app>type nul > urls.py                                                                                                                                                                                                                                      (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps\users_app>cd ..                                                                                                                           (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps>cd ..                                                                                                                                     (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>code .                                                                                                                                         (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py makemigrations                                                                                                                       Traceback (most recent call last):                                                                                        File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\manage.py", line 22, in <module>                                                                                                                          execute_from_command_line(sys.argv)                                                                                   File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line                                                                   utility.execute()                                                                                                     File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 341, in execute                                                                                     django.setup()                                                                                                        File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\__init__.py", line 27, in setup                                                                                                        apps.populate(settings.INSTALLED_APPS)                                                                                File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\apps\registry.py", line 108, in populate                                                                                               app_config.import_models(all_models)                                                                                  File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\apps\config.py", line 199, in import_models                                                                                            self.models_module = import_module(models_module_name)                                                                File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps\users_app\models.py", line 4, in <module>                                                                                                            class User(models.Model):                                                                                             File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps\users_app\models.py", line 8, in User                                                                                                                age = models.Integer()                                                                                              AttributeError: module 'django.db.models' has no attribute 'Integer'                                                                                                                                                                            (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py makemigrations                                                                                                                       Traceback (most recent call last):                                                                                        File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\manage.py", line 22, in <module>                                                                                                                          execute_from_command_line(sys.argv)                                                                                   File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line                                                                   utility.execute()                                                                                                     File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 359, in execute                                                                                     self.fetch_command(subcommand).run_from_argv(self.argv)                                                               File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 305, in run_from_argv                                                                                   self.execute(*args, **cmd_options)                                                                                    File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 353, in execute                                                                                         self.check()                                                                                                          File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 385, in check                                                                                           include_deployment_checks=include_deployment_checks,                                                                  File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 372, in _run_checks                                                                                     return checks.run_checks(**kwargs)                                                                                    File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks                                                                                       new_errors = check(app_configs=app_configs)                                                                           File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config                                                                                     return check_resolver(resolver)                                                                                       File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver                                                                                       for pattern in resolver.url_patterns:                                                                                 File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\functional.py", line 35, in __get__                                                                                              res = instance.__dict__[self.name] = self.func(instance)                                                              File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\urls\resolvers.py", line 310, in url_patterns                                                                                          patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)                                           File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\functional.py", line 35, in __get__                                                                                              res = instance.__dict__[self.name] = self.func(instance)                                                              File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\urls\resolvers.py", line 303, in urlconf_module                                                                                        return import_module(self.urlconf_name)                                                                               File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\single_model_orm\urls.py", line 21, in <module>                                                                                                           url(r'^', include('apps.users_app.urls'))                                                                             File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\conf\urls\__init__.py", line 50, in include                                                                                            urlconf_module = import_module(urlconf_module)                                                                        File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps\users_app\urls.py", line 2, in <module>                                                                                                              from apps import views                                                                                              ImportError: cannot import name 'views' from 'apps' (unknown location)                                                                                                                                                                          (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py makemigrations                                                                                                                       Traceback (most recent call last):                                                                                        File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\manage.py", line 22, in <module>                                                                                                                          execute_from_command_line(sys.argv)                                                                                   File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line                                                                   utility.execute()                                                                                                     File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 359, in execute                                                                                     self.fetch_command(subcommand).run_from_argv(self.argv)                                                               File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 305, in run_from_argv                                                                                   self.execute(*args, **cmd_options)                                                                                    File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 353, in execute                                                                                         self.check()                                                                                                          File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 385, in check                                                                                           include_deployment_checks=include_deployment_checks,                                                                  File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 372, in _run_checks                                                                                     return checks.run_checks(**kwargs)                                                                                    File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks                                                                                       new_errors = check(app_configs=app_configs)                                                                           File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config                                                                                     return check_resolver(resolver)                                                                                       File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver                                                                                       for pattern in resolver.url_patterns:                                                                                 File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\functional.py", line 35, in __get__                                                                                              res = instance.__dict__[self.name] = self.func(instance)                                                              File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\urls\resolvers.py", line 310, in url_patterns                                                                                          patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)                                           File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\functional.py", line 35, in __get__                                                                                              res = instance.__dict__[self.name] = self.func(instance)                                                              File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\urls\resolvers.py", line 303, in urlconf_module                                                                                        return import_module(self.urlconf_name)                                                                               File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\single_model_orm\urls.py", line 21, in <module>                                                                                                           url(r'^', include('apps.users_app.urls'))                                                                             File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\conf\urls\__init__.py", line 50, in include                                                                                            urlconf_module = import_module(urlconf_module)                                                                        File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 724, in exec_module                                                 File "<frozen importlib._bootstrap_external>", line 860, in get_code                                                    File "<frozen importlib._bootstrap_external>", line 791, in source_to_code                                              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps\users_app\urls.py", line 2                                                                                                                           from * import views                                                                                                          ^                                                                                                              SyntaxError: invalid syntax                                                                                                                                                                                                                     (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py makemigrations                                                                                                                       Traceback (most recent call last):                                                                                        File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\manage.py", line 22, in <module>                                                                                                                          execute_from_command_line(sys.argv)                                                                                   File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line                                                                   utility.execute()                                                                                                     File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 359, in execute                                                                                     self.fetch_command(subcommand).run_from_argv(self.argv)                                                               File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 305, in run_from_argv                                                                                   self.execute(*args, **cmd_options)                                                                                    File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 353, in execute                                                                                         self.check()                                                                                                          File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 385, in check                                                                                           include_deployment_checks=include_deployment_checks,                                                                  File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 372, in _run_checks                                                                                     return checks.run_checks(**kwargs)                                                                                    File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks                                                                                       new_errors = check(app_configs=app_configs)                                                                           File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config                                                                                     return check_resolver(resolver)                                                                                       File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver                                                                                       for pattern in resolver.url_patterns:                                                                                 File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\functional.py", line 35, in __get__                                                                                              res = instance.__dict__[self.name] = self.func(instance)                                                              File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\urls\resolvers.py", line 310, in url_patterns                                                                                          patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)                                           File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\functional.py", line 35, in __get__                                                                                              res = instance.__dict__[self.name] = self.func(instance)                                                              File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\urls\resolvers.py", line 303, in urlconf_module                                                                                        return import_module(self.urlconf_name)                                                                               File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\single_model_orm\urls.py", line 21, in <module>                                                                                                           url(r'^', include('apps.users_app.urls'))                                                                             File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\conf\urls\__init__.py", line 50, in include                                                                                            urlconf_module = import_module(urlconf_module)                                                                        File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps\users_app\urls.py", line 2, in <module>                                                                                                              from users_app import views                                                                                         ModuleNotFoundError: No module named 'users_app'                                                                                                                                                                                                (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py makemigrations                                                                                                                       Traceback (most recent call last):                                                                                        File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\manage.py", line 22, in <module>                                                                                                                          execute_from_command_line(sys.argv)                                                                                   File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line                                                                   utility.execute()                                                                                                     File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 359, in execute                                                                                     self.fetch_command(subcommand).run_from_argv(self.argv)                                                               File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 305, in run_from_argv                                                                                   self.execute(*args, **cmd_options)                                                                                    File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 353, in execute                                                                                         self.check()                                                                                                          File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 385, in check                                                                                           include_deployment_checks=include_deployment_checks,                                                                  File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 372, in _run_checks                                                                                     return checks.run_checks(**kwargs)                                                                                    File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks                                                                                       new_errors = check(app_configs=app_configs)                                                                           File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config                                                                                     return check_resolver(resolver)                                                                                       File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver                                                                                       for pattern in resolver.url_patterns:                                                                                 File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\functional.py", line 35, in __get__                                                                                              res = instance.__dict__[self.name] = self.func(instance)                                                              File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\urls\resolvers.py", line 310, in url_patterns                                                                                          patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)                                           File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\functional.py", line 35, in __get__                                                                                              res = instance.__dict__[self.name] = self.func(instance)                                                              File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\urls\resolvers.py", line 303, in urlconf_module                                                                                        return import_module(self.urlconf_name)                                                                               File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\single_model_orm\urls.py", line 21, in <module>                                                                                                           url(r'^', include('apps.users_app.urls'))                                                                             File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\conf\urls\__init__.py", line 50, in include                                                                                            urlconf_module = import_module(urlconf_module)                                                                        File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps\users_app\urls.py", line 2, in <module>                                                                                                              import views                                                                                                        ModuleNotFoundError: No module named 'views'                                                                                                                                                                                                    (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py makemigrations                                                                                                                       Traceback (most recent call last):                                                                                        File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\manage.py", line 22, in <module>                                                                                                                          execute_from_command_line(sys.argv)                                                                                   File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line                                                                   utility.execute()                                                                                                     File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 359, in execute                                                                                     self.fetch_command(subcommand).run_from_argv(self.argv)                                                               File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 305, in run_from_argv                                                                                   self.execute(*args, **cmd_options)                                                                                    File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 353, in execute                                                                                         self.check()                                                                                                          File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 385, in check                                                                                           include_deployment_checks=include_deployment_checks,                                                                  File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\management\base.py", line 372, in _run_checks                                                                                     return checks.run_checks(**kwargs)                                                                                    File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks                                                                                       new_errors = check(app_configs=app_configs)                                                                           File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config                                                                                     return check_resolver(resolver)                                                                                       File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver                                                                                       for pattern in resolver.url_patterns:                                                                                 File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\functional.py", line 35, in __get__                                                                                              res = instance.__dict__[self.name] = self.func(instance)                                                              File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\urls\resolvers.py", line 310, in url_patterns                                                                                          patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)                                           File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\functional.py", line 35, in __get__                                                                                              res = instance.__dict__[self.name] = self.func(instance)                                                              File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\urls\resolvers.py", line 303, in urlconf_module                                                                                        return import_module(self.urlconf_name)                                                                               File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\single_model_orm\urls.py", line 21, in <module>                                                                                                           url(r'^', include('apps.users_app.urls'))                                                                             File "C:\Users\kevin\Desktop\codingDojo\Python Stack\my_environments\djangoPy3Env\lib\site-packages\django\conf\urls\__init__.py", line 50, in include                                                                                            urlconf_module = import_module(urlconf_module)                                                                        File "C:\Users\kevin\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm\apps\users_app\urls.py", line 5, in <module>                                                                                                              url(r'^', views.default)                                                                                            AttributeError: module 'apps.users_app.views' has no attribute 'default'                                                                                                                                                                        (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py makemigrations                                                                                                                       Migrations for 'users_app':                                                                                               apps\users_app\migrations\0001_initial.py:                                                                                - Create model User                                                                                                                                                                                                                         (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py migrate      Operations to perform:                                                                                                    Apply all migrations: admin, auth, contenttypes, sessions, users_app                                                  Running migrations:                                                                                                       Rendering model states... DONE                                                                                          Applying contenttypes.0001_initial... OK                                                                                Applying auth.0001_initial... OK                                                                                        Applying admin.0001_initial... OK                                                                                       Applying admin.0002_logentry_remove_auto_add... OK                                                                      Applying contenttypes.0002_remove_content_type_name... OK                                                               Applying auth.0002_alter_permission_name_max_length... OK                                                               Applying auth.0003_alter_user_email_max_length... OK                                                                    Applying auth.0004_alter_user_username_opts... OK                                                                       Applying auth.0005_alter_user_last_login_null... OK                                                                     Applying auth.0006_require_contenttypes_0002... OK                                                                      Applying auth.0007_alter_validators_add_error_messages... OK                                                            Applying auth.0008_alter_user_username_max_length... OK                                                                 Applying sessions.0001_initial... OK                                                                                    Applying users_app.0001_initial... OK                                                                                                                                                                                                         (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py shell        Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32                       Type "help", "copyright", "credits" or "license" for more information.                                                  (InteractiveConsole)                                                                                                    >>> from apps.users_app.models import *                                                                                 >>> Users.objects.create(first_name="Kevin", last_name="Cox",email_address="kevin.kvc34@gmail.com",age=19               ... )                                                                                                                   Traceback (most recent call last):                                                                                        File "<console>", line 1, in <module>                                                                                 NameError: name 'Users' is not defined                                                                                  >>> User.objects.create(first_name="Kevin", last_name="Cox",email_address="kevin.kvc34@gmail.com",age=19)               <User: User object>                                                                                                     >>> User.objects.create(first_name="Kyla", last_name="Mcginnis",email_address="kmcginnis@gmail.com",age=19)             <User: User object>                                                                                                     >>> User.objects.create(first_name="Tyler", last_name="Kelly",email_address="tkelly@gmail.com",age=20)                  <User: User object>                                                                                                     >>> User.objects.get(id=2)                                                                                              <User: User object>                                                                                                     >>> User.objects.all()                                                                                                  <QuerySet [<User: User object>, <User: User object>, <User: User object>]>                                              >>> User.objects.all()                                                                                                  <QuerySet [<User: User object>, <User: User object>, <User: User object>]>                                              >>> exit()                                                                                                                                                                                                                                      (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py makemigrations                                                                                                                       No changes detected                                                                                                                                                                                                                             (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>migrate                'migrate' is not recognized as an internal or external command,                                                         operable program or batch file.                                                                                                                                                                                                                 (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py migrate      Operations to perform:                                                                                                    Apply all migrations: admin, auth, contenttypes, sessions, users_app                                                  Running migrations:                                                                                                       No migrations to apply.                                                                                                                                                                                                                       (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py shell        Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32                       Type "help", "copyright", "credits" or "license" for more information.                                                  (InteractiveConsole)                                                                                                    >>> User.objects.all()                                                                                                  Traceback (most recent call last):                                                                                        File "<console>", line 1, in <module>                                                                                 NameError: name 'User' is not defined                                                                                   >>> from apps.users_app.models import *                                                                                 >>> User.objects.all()                                                                                                  <QuerySet [>>>User Information: Kevin Cox, kevin.kvc34@gmail.com, 19<<<, >>>User Information: Kyla Mcginnis, kmcginnis@gmail.com, 19<<<, >>>User Information: Tyler Kelly, tkelly@gmail.com, 20<<<]>                                            >>> exit()                                                                                                                                                                                                                                      (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>migrate                'migrate' is not recognized as an internal or external command,                                                         operable program or batch file.                                                                                                                                                                                                                 (djangoPy3Env) C:\Users\kevin\Desktop\codingDojo\Python Stack\django\django_orm\single_model_orm>manage.py shell        Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32                       Type "help", "copyright", "credits" or "license" for more information.                                                  (InteractiveConsole)                                                                                                    >>> from apps.users_app.models import *                                                                                 >>> User.objects.all()                                                                                                  <QuerySet [>>>User Information: Kevin Cox, kevin.kvc34@gmail.com, 19, >>>User Information: Kyla Mcginnis, kmcginnis@gmail.com, 19, >>>User Information: Tyler Kelly, tkelly@gmail.com, 20]>                                                     >>> User.objects.first()                                                                                                >>>User Information: Kevin Cox, kevin.kvc34@gmail.com, 19                                                               >>> User.objects.last()                                                                                                 >>>User Information: Tyler Kelly, tkelly@gmail.com, 20                                                                  >>> User.objects.get(id=3)                                                                                              >>>User Information: Tyler Kelly, tkelly@gmail.com, 20                                                                  >>> tyler=User.objects.get(id=3)                                                                                        >>> tyler.last_name="Pancakes"                                                                                          >>> tyler.save()                                                                                                        >>> User.objects.get(id=3)                                                                                              >>>User Information: Tyler Pancakes, tkelly@gmail.com, 20                                                               >>> kyla=User.objects.get(id=2)                                                                                         >>> kyla.delete()                                                                                                       (1, {'users_app.User': 1})                                                                                              >>> User.objects.all()                                                                                                  <QuerySet [>>>User Information: Kevin Cox, kevin.kvc34@gmail.com, 19, >>>User Information: Tyler Pancakes, tkelly@gmail.com, 20]>                                                                                                               >>> User.objects.all().order_by("first_name")                                                                           <QuerySet [>>>User Information: Kevin Cox, kevin.kvc34@gmail.com, 19, >>>User Information: Tyler Pancakes, tkelly@gmail.com, 20]>                                                                                                               >>> User.objects.all().order_by("age")                                                                                  <QuerySet [>>>User Information: Kevin Cox, kevin.kvc34@gmail.com, 19, >>>User Information: Tyler Pancakes, tkelly@gmail.com, 20]>                                                                                                               >>> User.objects.all().order_by("-first_name")                                                                          <QuerySet [>>>User Information: Tyler Pancakes, tkelly@gmail.com, 20, >>>User Information: Kevin Cox, kevin.kvc34@gmail.com, 19]>                                                                                                               >>>  